### PR TITLE
docs: add intro doc

### PR DESCRIPTION
**Pull request by SahilAujla**
https://github.com/OMGWINNING/aa-sdk-staging/assets/83442423/3777c343-52fb-4820-9612-9ada6596adf1

TODO: Add links to signer docs for Lit Protocol, Privy etc. once they are added.

### CODE REVIEW

**Review by rthomare — APPROVED** [review]

**Review by avasisht23 — APPROVED** [review]
lgtm, but watch if any changes happen in the notion per Will's comments: https://www.notion.so/Overview-c25bebdd6e3d4165bf349b102978a7eb

**Comment by willhennessy** [comment]
1. can we reduce the width of the stack diagram by 30%?
2. let's remove the with/without diagram. i think it adds more complexity than it helps

thanks sahil!!

**Comment by SahilAujla** [comment]
@willhennessy I've removed the with / without diagram and now just waiting for the new smaller image so I can replace that with the existing one ( that's being rendered very big )

**Comment by moldy530** [comment]
one other option for the image is to use an `` tag directly in the markdown and set the styles on it directly for height and width, that way we don't have to block on design (though I think it's already in flight)

**Comment by SahilAujla** [comment]
image

**Review by moldy530 — APPROVED** [review]

**Pull request merged**
